### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ri0t** [plus-me/backend#1]
Aloha, @dbrockmann - gibts schon neuigkeiten? Also, bzgl.
* OAuth provider?
* Rebuild mit node? Oder doch Django erweitern? 

Wäre gut, da langsam etwas Klarheit zu haben - an einem ersten Deployment-System wird schon gearbeitet :-)

**Comment by dbrockmann** [comment]
Ein vollständiges Auth-Backend zum Selbsthosten: https://fusionauth.io/. Kostenlos für unsere Nutzen, ist jedoch nicht Open-Source. Läuft gerade zum Testen in Google Cloud und scheint auch gut skalieren zu können.

Ich hatte schon an einem Rebuild mit Node gearbeitet, aber beim Meeting am Dienstag haben wir beschlossen das alte Backend zu behalten. An Authentifizierung müssten dann nur noch die JWTs validiert werden.
